version: "3.9"

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    env_file:
      - .env 
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      APP_PORT: ${APP_PORT}

    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./services/user-service/config/config:/app/config  
    networks:
      - accounting-network
    depends_on:
      - db

  # accounting-service:
  #   build:
  #     context: ./services/accounting-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8002:8002"
  #   env_file:
  #     - ./services/accounting-service/config/.env
  #   networks:
  #     - accounting-network
  #   depends_on:
  #     - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accounting-network
    restart: always  

networks:
  accounting-network:
    driver: bridge

volumes:
  postgres-data:
