version: "3.9"

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./services/user-service/config/.env
    networks:
      - accounting-network
    depends_on:
      - db

  accounting-service:
    build:
      context: ./services/accounting-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./services/accounting-service/config/.env
    networks:
      - accounting-network
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accounting-network

networks:
  accounting-network:
    driver: bridge

volumes:
  postgres-data:
